// AUTO-GENERATED by scripts/generate-openapi-types.mjs.
// Source: ../contracts/answer_receipt.schema.json and contracts/openapi.yaml.
// Do not edit by hand.

export type MoneyString = string;
export type AnswerStatus = 'verified' | 'qualified' | 'needs_clarification' | 'not_answerable' | 'no_matching_rows' | 'error';
export type ValidationCheckStatus = 'pass' | 'warn' | 'fail' | 'not_applicable';
export type ConfidenceState = 'verified' | 'qualified' | 'blocked';

export interface ApiColumn {
  key: string;
  label: string;
  type?: string;
}

export interface ValidationCheck {
  check_id: string;
  label: string;
  status: ValidationCheckStatus;
  details: string;
}

export interface WarningItem {
  code: string;
  severity?: string;
  message: string;
  record_ids?: string[];
}

export interface AnswerReceipt {
  schema_version: '1.0.0';
  query_id: string;
  conversation_id?: string | null;
  turn_id?: string | null;
  status: AnswerStatus;
  answer: {
    plain_language: string;
    value: MoneyString | number | null;
    currency: 'INR' | null;
    unit: 'currency' | 'count' | 'percent' | 'records' | 'metadata' | 'none';
  };
  primary_metric: null | {
    metric_id: string;
    label: string;
    value: MoneyString | number | null;
    formatted_value: string;
  };
  interpretation: {
    canonical_query_plan: Record<string, unknown> | null;
    human_readable_steps: string[];
    assumptions: string[];
    context_changes: string[];
  };
  breakdown: {
    columns: ApiColumn[];
    rows: Array<Record<string, unknown>>;
    total_row: Record<string, unknown> | null;
  };
  lineage: {
    company_id: string;
    dataset_version: string;
    data_as_of: string;
    executed_query_name: string | null;
    source_row_count: number;
    source_record_ids: string[];
    source_record_ids_truncated?: boolean;
    source_record_ids_hash: string;
    database_snapshot_id?: string;
  };
  validation: {
    passed: boolean;
    checks: ValidationCheck[];
  };
  confidence: {
    state: ConfidenceState;
    score: number | null;
    factors: Array<Record<string, unknown>>;
  };
  warnings: WarningItem[];
  clarification?: Record<string, unknown> | null;
  records_preview: {
    columns: ApiColumn[];
    rows: Array<Record<string, unknown>>;
    next_cursor: string | null;
    total_count: number;
  };
  exports: {
    csv_url: string | null;
    xlsx_url: string | null;
    expires_at: string | null;
  };
  timings: {
    total_ms: number;
    parse_ms: number;
    query_ms: number;
    validation_ms: number;
    compose_ms: number;
    model_id?: string | null;
    input_tokens?: number | null;
    output_tokens?: number | null;
    cache_status?: 'hit' | 'miss' | 'bypass';
  };
}

export interface DataHealthCheck {
  check_id: string;
  category: 'freshness' | 'schema' | 'referential_integrity' | 'coverage' | 'duplicates' | 'precision' | 'reconciliation';
  status: 'pass' | 'warning' | 'fail';
  label: string;
  details: string;
  affected_record_count: number;
  sample_record_ids?: string[];
}

export interface DataHealthResponse {
  overall_state: 'healthy' | 'warning' | 'error';
  data_as_of: string;
  checks: DataHealthCheck[];
}

export interface MetaResponse {
  company: {
    company_id: string;
    display_name: string;
    currency: 'INR';
    timezone: 'Asia/Kolkata';
    fiscal_year_start_month: number;
    synthetic?: boolean;
  };
  dataset: {
    version: string;
    data_as_of: string;
    max_posting_date: string;
    max_payout_date?: string;
    freshness_state: 'fresh' | 'stale' | 'unknown';
    generated_at?: string;
  };
  supported_metrics: Array<Record<string, unknown>>;
  supported_examples: string[];
  versions?: Record<string, string>;
  features?: Record<string, boolean>;
}

export interface ProblemDetails {
  type: string;
  title: string;
  status: number;
  detail: string;
  trace_id: string;
  field_errors?: Record<string, unknown>;
}
