#!/usr/bin/env python3
"""Validate repository structure, contracts, backlog and runtime/gold isolation."""
from __future__ import annotations

import csv
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REQUIRED = [
    'README.md','AGENTS.md','docs/MASTER_PRODUCT_IMPLEMENTATION_SPEC.md','project_backlog.csv',
    'contracts/openapi.yaml','contracts/query_plan.schema.json','contracts/answer_receipt.schema.json',
    'contracts/semantic_metrics.yaml','data/dataset_manifest.json','database/schema.sql',
    'docs/UI_UX_SPEC.md','docs/BACKEND_QUERY_ENGINE_SPEC.md','docs/BUG_AND_QA_PLAYBOOK.md',
]
errors: list[str] = []
warnings: list[str] = []

for rel in REQUIRED:
    if not (ROOT / rel).is_file():
        errors.append(f'missing required file: {rel}')

schemas: dict[Path, dict] = {}
for p in (ROOT / 'contracts').glob('*.json'):
    try:
        data = json.loads(p.read_text(encoding='utf-8'))
        if p.name.endswith('.schema.json'):
            schemas[p] = data
    except Exception as exc:
        errors.append(f'invalid JSON {p.relative_to(ROOT)}: {exc}')

try:
    from jsonschema import Draft202012Validator  # type: ignore
except ImportError:
    Draft202012Validator = None
    warnings.append('jsonschema not installed; meta-schema/sample checks skipped')
if Draft202012Validator:
    for p, schema in schemas.items():
        try:
            Draft202012Validator.check_schema(schema)
        except Exception as exc:
            errors.append(f'invalid JSON Schema {p.relative_to(ROOT)}: {exc}')
    try:
        sample = json.loads((ROOT/'contracts/sample_verified_answer_receipt.json').read_text())
        receipt_schema = schemas[ROOT/'contracts/answer_receipt.schema.json']
        sample_errors = sorted(Draft202012Validator(receipt_schema).iter_errors(sample), key=lambda e: list(e.path))
        for e in sample_errors:
            errors.append(f'sample receipt schema error at {list(e.path)}: {e.message}')
    except Exception as exc:
        errors.append(f'could not validate sample receipt: {exc}')

try:
    import yaml  # type: ignore
except ImportError:
    yaml = None
    warnings.append('PyYAML not installed; YAML parse check skipped')
if yaml:
    for rel in ['contracts/openapi.yaml','contracts/semantic_metrics.yaml']:
        try:
            data = yaml.safe_load((ROOT / rel).read_text(encoding='utf-8'))
            if not isinstance(data, dict):
                errors.append(f'YAML root is not an object: {rel}')
        except Exception as exc:
            errors.append(f'invalid YAML {rel}: {exc}')

# Backlog IDs and dependencies.
try:
    with (ROOT/'project_backlog.csv').open(newline='',encoding='utf-8') as f:
        tasks=list(csv.DictReader(f))
    ids=[t['ticket_id'] for t in tasks]
    if len(ids) != len(set(ids)):
        errors.append('duplicate ticket IDs in project_backlog.csv')
    idset=set(ids)
    for t in tasks:
        for dep in [d.strip() for d in t.get('dependencies','').split(';') if d.strip()]:
            if dep not in idset:
                errors.append(f"unknown dependency {dep} on {t['ticket_id']}")
            if dep == t['ticket_id']:
                errors.append(f"self dependency on {t['ticket_id']}")
        if not t.get('acceptance_criteria') or not t.get('tests_required'):
            errors.append(f"missing acceptance/tests on {t['ticket_id']}")
except Exception as exc:
    errors.append(f'could not validate backlog: {exc}')

for p in ROOT.rglob('*'):
    if p.is_dir() and p.name == '__pycache__':
        errors.append(f'generated bytecode directory committed: {p.relative_to(ROOT)}')

# Runtime paths may mention the prohibition in docs/tests, but app source may not read gold.
for base in [ROOT / 'backend', ROOT / 'frontend']:
    if not base.exists():
        continue
    for p in base.rglob('*'):
        if not p.is_file() or p.suffix.lower() not in {'.py','.ts','.tsx','.js','.jsx'}:
            continue
        text = p.read_text(encoding='utf-8', errors='ignore')
        if re.search(r'evaluation[\/]expected_|expected_aggregates', text):
            errors.append(f'runtime gold dependency: {p.relative_to(ROOT)}')

if warnings:
    for w in warnings:
        print(f'WARN: {w}')
if errors:
    print('Repository validation FAILED:')
    for e in errors:
        print(f'  - {e}')
    sys.exit(1)
print('PASS: repository structure, contracts, sample receipt, backlog dependencies, and runtime/gold isolation are valid.')
